application: webgradients-go
version: 2
runtime: go
api_version: 3

handlers:
- url: /site_media
  static_dir: site_media

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app
